version: '3.2'
services:

  smart-launcher: # SMART Launcher ---------------------------------------------
    #image: smartonfhir/smart-launcher:r4
    build: ../smart-launcher
    restart: unless-stopped
    environment:
      NODE_ENV               : "production"
      LAUNCHER_BASE_URL      : "http://${HOST}:${LAUNCHER_PORT}"
      BASE_URL               : "http://${HOST}:${LAUNCHER_PORT}"
      AUTH_BASE_URL          : "https://auth.tcpdev.org/oxauth/restv1"
      FHIR_SERVER_R4         : "http://${HOST}:${HAPI_PORT_R4}/baseR4"
      FHIR_SERVER_R4_INTERNAL: "https://launch.smarthealthit.org/v/r4/sim/eyJrIjoiMSIsImoiOiIxIn0/fhir"
      DISABLE_SANDBOXES      : "1"
      CDS_SANDBOX_URL        : "https://sandbox.cds-hooks.org"
      PICKER_CONFIG_R4       : "r4-local"
      PICKER_ORIGIN          : "http://${HOST}:${PATIENT_BROWSER_PORT}"
      STU4_ENABLED           : "${R4_ENABLED}"
    ports:
      - "${LAUNCHER_PORT}:80"
      - "9229:9229"
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "."
    depends_on:
      - patient-browser
      - fhir-viewer
    # volumes:
      # - "../smart-launcher:/app"

  patient-browser: # Patient Browser -------------------------------------------
    image: smartonfhir/patient-browser:node
    ports:
      - "${PATIENT_BROWSER_PORT}:80"
    volumes:
      - ./patient-browser:/usr/share/nginx/html/config
    environment:
      LAUNCHER_PORT   : "${LAUNCHER_PORT}"
      FHIR_VIEWER_PORT: "${FHIR_VIEWER_PORT}"
      HAPI_PORT_R4    : "${HAPI_PORT_R4}"
      HOST            : "${HOST}"
    command: sh -c "envsubst < /usr/share/nginx/html/config/dstu2-local.tpl > /usr/share/nginx/html/config/dstu2-local.json5 && envsubst < /usr/share/nginx/html/config/stu3-local.tpl > /usr/share/nginx/html/config/stu3-local.json5 && nginx -g 'daemon off;'"

  fhir-viewer: # Fhir Viewer ---------------------------------------------------
    image: smartonfhir/fhir-viewer
    ports:
      - "${FHIR_VIEWER_PORT}:80"
    volumes:
      - ./fhir-viewer:/usr/share/nginx/html/config
    environment:
      HOST: "${HOST}"
    command: sh -c "envsubst < /usr/share/nginx/html/config/known-servers.tpl > /usr/share/nginx/html/known-servers.js && nginx -g 'daemon off;'"

  index: # Index page ----------------------------------------------------------
    image: nginx:alpine
    ports:
      - "${CONTROL_PANEL_PORT}:80"
    volumes:
      - ./www:/usr/share/nginx/html
    environment:
      LAUNCHER_PORT       : "${LAUNCHER_PORT}"
      HAPI_PORT_R4        : "${HAPI_PORT_R4}"
      PATIENT_BROWSER_PORT: "${PATIENT_BROWSER_PORT}"
      FHIR_VIEWER_PORT    : "${FHIR_VIEWER_PORT}"
      STU2_ENABLED        : "false"
      STU3_ENABLED        : "false"
      R4_ENABLED          : "true"
      HOST                : "${HOST}"

      ISSUES_URL          : "https://github.com/smart-on-fhir/smart-dev-sandbox/issues"
    command: sh -c "envsubst < /usr/share/nginx/html/template.html > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
